playbook_name: "T1190 - Public-Facing Application Exploit: Investigation & Triage"
tactic: "Initial Access"
technique_id: "T1190"
technique_name: "Public-Facing Application Exploit"
description: >
  Investigation-centric playbook to guide SOC analysts in identifying,
  triaging, and responding to exploitation attempts against public-facing applications.

investigation_steps:
  - step_number: 1
    title: "Trigger Review"
    description: >
      Validate alert context from SIEM or WAF. Determine if the alert is true positive.
    checklist:
      - "What is the targeted application endpoint (URL path, HTTP method)?"
      - "Does the request contain known exploit payloads (e.g., cmd=, ${jndi:, ../)?"
      - "Is the source IP known for abuse or scanning activity?"
      - "Is this request anomalous compared to historical traffic to the same endpoint?"
    data_sources:
      - "Web Server Logs"
      - "WAF Logs"
      - "Threat Intelligence"
      - "SIEM Alert Details"

  - step_number: 2
    title: "Payload Inspection"
    description: >
      Deep-dive into payload to identify attack type and exploit technique.
    checklist:
      - "Does the payload contain file uploads, SQLi, RCE, SSRF, or LFI indicators?"
      - "Is there evidence of attempted code execution or shell upload?"
      - "Is the user-agent or referrer abnormal or tool-based (e.g., curl, python, sqlmap)?"
    data_sources:
      - "WAF Packet Capture (if available)"
      - "Decoded Payload Data"
      - "Custom Regex Matching Rules"
      - "Application Firewall Signatures"

  - step_number: 3
    title: "Exploit Success Check"
    description: >
      Determine if the exploit attempt was successful.
    checklist:
      - "Were new or suspicious files created in the web directory?"
      - "Was a new process spawned by the web server (e.g., bash, cmd.exe)?"
      - "Did the endpoint generate outbound connections (beaconing or C2)?"
      - "Did authentication tokens or sessions change post-attempt?"
    data_sources:
      - "EDR on Web Server"
      - "Process Creation Logs"
      - "Outbound Proxy/DNS Logs"
      - "Web Server File Integrity Monitoring"

  - step_number: 4
    title: "Session & Scope Analysis"
    description: >
      Determine user impact, lateral movement, and breadth of the compromise.
    checklist:
      - "Was the attacker able to pivot to another internal resource?"
      - "Any signs of session hijacking or credential abuse?"
      - "Did they access sensitive routes (e.g., /admin, /db, /config)?"
    data_sources:
      - "Web Application Logs"
      - "Authentication Logs"
      - "NetFlow/PCAP"
      - "SIEM Correlation Events"

triage_labels:
  - severity_levels:
      - "Low: Attempted scan or malformed request with no exploit signature."
      - "Medium: Known exploit string present but no evidence of success."
      - "High: Confirmed execution (webshell, process spawn, file write)."
  - confidence_levels:
      - "High: Payload matches known CVE and server behavior aligns with exploit."
      - "Medium: Suspicious activity without full exploit context."
      - "Low: Noisy or generic probing, low IOC fidelity."

ioc_types:
  - "Source IP address"
  - "Exploit strings (regex patterns)"
  - "User-Agent strings"
  - "New file names or paths on web server"
  - "Process names launched by web app"
  - "Outbound domains or IPs"

queries/examples:
  - name: "Webshell Detection"
    query: >
      file.path:/var/www/** AND (file.name:*.php OR *.jsp) AND process.parent.name:apache2
  - name: "Suspicious Web Request"
    query: >
      http.request.uri_path:(*.php OR *.jsp) AND http.request.body:(cmd= OR ${jndi: OR ../../)
  - name: "RCE Behavior"
    query: >
      process.parent.name:(apache2 OR nginx OR httpd) AND process.name:(bash OR powershell OR cmd.exe)

automation_hooks:
  - "Enrich IP with threat intel (VirusTotal, AbuseIPDB, etc.)"
  - "Trigger EDR process scan on web server"
  - "Auto-tag alert in SIEM if CVE matches WAF exploit signature"
  - "Auto-block IP in firewall/WAF if triage level is High"

analyst_guidance:
  - "Use historical traffic for this endpoint to identify anomalies."
  - "Confirm any file creation or process execution not matching deployment pattern."
  - "Coordinate with app/dev team to understand expected vs. abnormal behavior."
  - "Treat verified file drops and process executions as HIGH confidence compromises."

reference_links:
  - "https://attack.mitre.org/techniques/T1190/"
  - "https://owasp.org/www-project-top-ten/"
  - "https://cwe.mitre.org/data/definitions/94.html"
  - "Vendor-specific WAF/CVE documentation"

review_cycle: "After major WAF rule updates or new 0-days affecting public apps"
